### ISSUE TITLE
Compilation Error Occured.

### ISSUE THREAD

**Issue by yama2akira** [deepmind/lab#10]
I ran the command on ubuntu/trusty64.
The error has occured.

```
$ bazel run :random_agent --define headless=false -- --length=10000 --width=640 --height=480
INFO: Found 1 target...
ERROR: /home/vagrant/lab/BUILD:980:1: C++ compilation of rule '//:deepmind_lab.so' failed: linux-sandbox failed: error executing command /home/vagrant/.cache/bazel/_bazel_vagrant/c1d0c0e8255f05e00abeeb68d70c5ac4/execroot/lab/_bin/linux-sandbox ... (remaining 48 argument(s) skipped).
python/dmlab_module.c:29:31: fatal error: numpy/arrayobject.h: No such file or directory
 #include "numpy/arrayobject.h"
                               ^
compilation terminated.
WARNING: Cannot delete sandbox directory after action execution: /home/vagrant/.cache/bazel/_bazel_vagrant/c1d0c0e8255f05e00abeeb68d70c5ac4/bazel-sandbox/867732be-eacb-4fb1-b1ab-3e24f38afc93-13 (java.io.IOException: /home/vagrant/.cache/bazel/_bazel_vagrant/c1d0c0e8255f05e00abeeb68d70c5ac4/bazel-sandbox/867732be-eacb-4fb1-b1ab-3e24f38afc93-13/execroot/lab (Device or resource busy)).
Target //:random_agent failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 48.362s, Critical Path: 4.48s
ERROR: Build failed. Not running target.

```
I've already installed numpy on python2.7. Please help.

**Comment by tkoeppe** [comment]
Did you install the development version of the package (the one ending in `-dev`)?

**Comment by yama2akira** [comment]
Not yet. so I installed numpy-dev as follows 
```
sudo apt-get –y install python2.7-dev  python-numpy-dev 
```

Compilation has done, however the error has occured.
```
$ bazel run :random_agent --define headless=false -- --length=10000 --width=640 --height=480
INFO: Found 1 target...
Target //:random_agent up-to-date:
  bazel-bin/random_agent
INFO: Elapsed time: 0.767s, Critical Path: 0.03s

INFO: Running command line: bazel-bin/random_agent '--length=10000' '--width=640' '--height=480'
ERROR: Non-zero return code '3' from command: Process exited with status 3.
```

**Comment by tkoeppe** [comment]
Can you run it directly and see what errors come up?

    ./bazel-bin/random_agent --length=10000 --width=640 --height=480

**Comment by tkoeppe** [comment]
@yama2akira: Do you still have this problem?

**Comment by heiner** [comment]
Also, could you make sure you run this from a computer with a running X server?

**Comment by yama2akira** [comment]
Sorry not to respond your support..
I ran it and the error has come up.
```
$ ./bazel-bin/random_agent --length=10000 --width=640 --height=480
Failed to open library! - ./libdmlab.so
./libdmlab.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/vagrant/lab/bazel-bin/random_agent.runfiles/org_deepmind_lab/python/random_agent.py", line 188, in <module>
    run(args.length, args.width, args.height, args.fps, args.level_script)
  File "/home/vagrant/lab/bazel-bin/random_agent.runfiles/org_deepmind_lab/python/random_agent.py", line 146, in run
    'height': str(height)
RuntimeError: Failed to connect RL API
```

**Comment by tkoeppe** [comment]
@yama2akira: Sorry, I gave bad instructions. Try this instead please:

    $ cd bazel-bin/random_agent.runfiles/org_deepmind_lab
    $ ./random_agent --length=10000 --width=640 --height=480

(The `libdmlab.so` file is in that directory.)

As Heiner said above, make sure you can connect to an X server if you compiled with anything other than `headless=osmesa`

**Comment by yama2akira** [comment]
Sorry, I didn't these commands on GUI environment(xserver). I connected with ssh CUI.
These commands works fine.

Thank you for your advice.

**Comment by tkoeppe** [comment]
Great, thanks for confirming!
