### ISSUE TITLE
Trouble running the random agent - No module named 'numpy'

### ISSUE THREAD

**Issue by lionminhu** [deepmind/lab#170]
Hello, earlier today, after installing DMLab and running
```bazel run :python_random_agent --define graphics=sdl -- --length=10000 --width=640 --height=480```,
I got
```INFO: Build completed successfully, 507 total actions```

Having confirmed that the build completed well, I came back and noticed that running the same random agent script results in the following error:
```bash
kbkim@user:~/research/dmlab/lab$ bazel run :python_random_agent --define graphics=sdl -- --length=10000 --width=640 --height=480
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "07315c19273cc3479ff58c7ae66c7a1ff2d65160f85689a9e1729a46566b2198"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /home/kbkim/.cache/bazel/_bazel_kbkim/0ebea18a78bccf4cf8b51f4ae8428669/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /home/kbkim/research/dmlab/lab/WORKSPACE:11:1
DEBUG: Rule 'com_google_absl' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "bad7c7b472ea1e5b4dc48874097e493cf694965fc9ae11d1cf590825bc162cf1"
DEBUG: Call stack for the definition of repository 'com_google_absl' which is a http_archive (rule definition at /home/kbkim/.cache/bazel/_bazel_kbkim/0ebea18a78bccf4cf8b51f4ae8428669/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /home/kbkim/research/dmlab/lab/WORKSPACE:17:1
INFO: Analyzed target //:python_random_agent (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:python_random_agent up-to-date:
  bazel-bin/python_random_agent
INFO: Elapsed time: 0.322s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Traceback (most recent call last):
  File "/home/kbkim/.cache/bazel/_bazel_kbkim/0ebea18a78bccf4cf8b51f4ae8428669/execroot/org_deepmind_lab/bazel-out/k8-fastbuild/bin/python_random_agent.runfiles/org_deepmind_lab/python/random_agent.py", line 24, in <module>
    import numpy as np
ImportError: No module named 'numpy'
```

I have Python 2.7.12 and Numpy 1.14.3, but I also have Python 3.6 installed, and the `python` command is linked to Python 3 currently. If that is what is causing the problem, is there a way to specify the version of Python to run with the `bazel` command?

I have confirmed that both `python-numpy` and `python-numpy-dev` are installed via `apt`.

**Comment by tkoeppe** [comment]
Can you check that the paths configured in `python.BUILD` match your system setup?

**Comment by lionminhu** [comment]
Thank you for the quick reply!
Referring to https://github.com/deepmind/lab/issues/32#issuecomment-350281599 and https://github.com/deepmind/lab/issues/32#issuecomment-350282667, I changed `python.BUILD` to below:
```
cc_library(
    name = "python",
    hdrs = glob([
        "include/python2.7/*.h",
        "local/lib/python2.7/dist-packages/numpy/core/include/**/*.h",
    ]),
    includes = [
        "include/python2.7",
        "local/lib/python2.7/dist-packages/numpy/core/include",
    ],
    visibility = ["//visibility:public"],
)
```
Running the random agent now results in the following error:
```bash
kbkim@user:~/research/dmlab/lab$ bazel run :python_random_agent
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "07315c19273cc3479ff58c7ae66c7a1ff2d65160f85689a9e1729a46566b2198"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /home/kbkim/.cache/bazel/_bazel_kbkim/0ebea18a78bccf4cf8b51f4ae8428669/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /home/kbkim/research/dmlab/lab/WORKSPACE:11:1
DEBUG: Rule 'com_google_absl' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "bad7c7b472ea1e5b4dc48874097e493cf694965fc9ae11d1cf590825bc162cf1"
DEBUG: Call stack for the definition of repository 'com_google_absl' which is a http_archive (rule definition at /home/kbkim/.cache/bazel/_bazel_kbkim/0ebea18a78bccf4cf8b51f4ae8428669/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /home/kbkim/research/dmlab/lab/WORKSPACE:17:1
INFO: Analyzed target //:python_random_agent (1 packages loaded, 123 targets configured).
INFO: Found 1 target...
INFO: From Linking deepmind_lab.so:
bazel-out/k8-fastbuild/bin/_objs/dmlab_so_loader/dmlab_so_loader.pic.o:dmlab_so_loader.cc:function (anonymous namespace)::make_unique_path(): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
Target //:python_random_agent up-to-date:
  bazel-bin/python_random_agent
INFO: Elapsed time: 0.731s, Critical Path: 0.32s
INFO: 2 processes: 2 linux-sandbox.
INFO: Build completed successfully, 3 total actions
INFO: Build completed successfully, 3 total actions
Traceback (most recent call last):
  File "/home/kbkim/.cache/bazel/_bazel_kbkim/0ebea18a78bccf4cf8b51f4ae8428669/execroot/org_deepmind_lab/bazel-out/k8-fastbuild/bin/python_random_agent.runfiles/org_deepmind_lab/python/random_agent.py", line 27, in <module>
    import deepmind_lab
ImportError: /home/kbkim/.cache/bazel/_bazel_kbkim/0ebea18a78bccf4cf8b51f4ae8428669/execroot/org_deepmind_lab/bazel-out/k8-fastbuild/bin/python_random_agent.runfiles/org_deepmind_lab/deepmind_lab.so: undefined symbol: PyCObject_Type
```

**Comment by tkoeppe** [comment]
Could you try a suitable set of Python3 paths?

Specifically, make sure you have Python3's numpy installed. I usually run this find command to find the location: `find -L /usr/include -type f -name arrayobject.h` That's because Numpy includes a header file called `arrayobject.h`, so the location of that header gives you a hint as to the location of the relevant Python header tree.

**Comment by lionminhu** [comment]
I've actually found the include paths (referring to [this](https://stackoverflow.com/a/35071359)) as below:
```
Python 3.6.9 (default, Jul  3 2019, 15:36:16)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sysconfig import get_paths
>>> from pprint import pprint
>>> info = get_paths()
>>> pprint(info)
{'data': '/usr',
 'include': '/usr/include/python3.6m',
 'platinclude': '/usr/include/python3.6m',
 'platlib': '/usr/lib/python3.6/site-packages',
 'platstdlib': '/usr/lib/python3.6',
 'purelib': '/usr/lib/python3.6/site-packages',
 'scripts': '/usr/bin',
 'stdlib': '/usr/lib/python3.6'}
>>> import numpy
>>> numpy.__file__
'/usr/local/lib/python3.6/dist-packages/numpy/__init__.py'
```

Editing `python.BUILD` as below:
```
cc_library(
    name = "python",
    hdrs = glob([
        "include/python3.6m/*.h",
        "local/lib/python3.6/dist-packages/numpy/**/*.h",
    ]),
    includes = [
        "include/python3.6m",
        "lib/python3.6/site-packages",
        "include/python3.6",
    ],
    visibility = ["//visibility:public"],
)
```

And running the random agent works fine:
```bash
kbkim@user:~/research/dmlab/lab$ bazel run :python_random_agent
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "07315c19273cc3479ff58c7ae66c7a1ff2d65160f85689a9e1729a46566b2198"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /home/kbkim/.cache/bazel/_bazel_kbkim/0ebea18a78bccf4cf8b51f4ae8428669/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /home/kbkim/research/dmlab/lab/WORKSPACE:11:1
DEBUG: Rule 'com_google_absl' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "bad7c7b472ea1e5b4dc48874097e493cf694965fc9ae11d1cf590825bc162cf1"
DEBUG: Call stack for the definition of repository 'com_google_absl' which is a http_archive (rule definition at /home/kbkim/.cache/bazel/_bazel_kbkim/0ebea18a78bccf4cf8b51f4ae8428669/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /home/kbkim/research/dmlab/lab/WORKSPACE:17:1
INFO: Analyzed target //:python_random_agent (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:python_random_agent up-to-date:
  bazel-bin/python_random_agent
INFO: Elapsed time: 0.267s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Starting random spring agent. Action spec: [{'min': -512, 'max': 512, 'name': 'LOOK_LEFT_RIGHT_PIXELS_PER_FRAME'}, {'min': -512, 'max': 512, 'name': 'LOOK_DOWN_UP_PIXELS_PER_FRAME'}, {'min': -1, 'max': 1, 'name': 'STRAFE_LEFT_RIGHT'}, {'min': -1, 'max': 1, 'name': 'MOVE_BACK_FORWARD'}, {'min': 0, 'max': 1, 'name': 'FIRE'}, {'min': 0, 'max': 1, 'name': 'JUMP'}, {'min': 0, 'max': 1, 'name': 'CROUCH'}]
Finished after 1000 steps. Total reward received is 0.000000
```

Thank you for your help!

**Comment by tkoeppe** [comment]
You're most welcome!
