### ISSUE TITLE
Issues testing the installation with a simple random agent.

### ISSUE THREAD

**Issue by varshantdhar** [deepmind/lab#211]
Running the last example from (https://github.com/deepmind/lab/blob/master/python/pip_package/README.md) first produces an error, complaining about the missing dm_env package. Resolving this with a pip install leads to another error 

` ImportError: dlopen(/Users/.../...//deepmind_lab.so, 2): image not found`

Here is the Traceback (most recent call last):

` File "/Users/.../.../.../agent.py", line 2, in <module>
    import deepmind_lab
  File "/Users/..../..../..../env/lib/python3.9/site-packages/deepmind_lab/__init__.py", line 28, in <module>
    _deepmind_lab = imp.load_dynamic(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/imp.py", line 342, in load_dynamic
    return _load(spec) `

What should I do to resolve this?

**Comment by tkoeppe** [comment]
Is this on Linux or on MacOS?

**Comment by varshantdhar** [comment]
Apologies I should’ve written that. It’s on a Mac OS Big Sur.

**Comment by tkoeppe** [comment]
The Mac build is only very poorly supported I'm afraid. If you can make progress on this, I'll happily patch things according to your instructions. I can basically only use the GitHub action runner to test that platform.
